INSERT INTO order_table VALUES (1,SYSTIMESTAMP,18000,'delivery',SYSTIMESTAMP,1,1);
INSERT INTO order_table VALUES (2,SYSTIMESTAMP,55000,'delivery',SYSTIMESTAMP,2,2);
INSERT INTO order_table VALUES (3,SYSTIMESTAMP,998,'delivery',SYSTIMESTAMP,3,3);
INSERT INTO order_table VALUES (4,SYSTIMESTAMP,1299,'delivery',SYSTIMESTAMP,4,4);
INSERT INTO order_table VALUES (5,SYSTIMESTAMP,1998,'delivery',SYSTIMESTAMP,5,5);
INSERT INTO order_table VALUES (6,SYSTIMESTAMP,2999,'delivery',SYSTIMESTAMP,6,6);
INSERT INTO order_table VALUES (7,SYSTIMESTAMP,3500,'delivery',SYSTIMESTAMP,7,7);
INSERT INTO order_table VALUES (8,SYSTIMESTAMP,1300,'delivery',SYSTIMESTAMP,8,8);
INSERT INTO order_table VALUES (9,SYSTIMESTAMP,4500,'delivery',SYSTIMESTAMP,9,9);
INSERT INTO order_table VALUES (10,SYSTIMESTAMP,2499,'delivery',SYSTIMESTAMP,10,10);

